const vehicles = [
  {name: 'Acura', image: './assets/acura_featured_logo.png'},
  {name: 'Alfa Romeo', image: './assets/alfaromeo_featured_logo.png'},
  {name: 'Aston Martin', image: './assets/astonmartin_featured_logo.png'},
  {name: 'Audi', image: './assets/audi_featured_logo.png'},
  {name: 'Bentley', image: './assets/bentley_featured_logo.png'},
  {name: 'BMW', image: './assets/bmw_featured_logo.png'},
  {name: 'Buick', image: './assets/buick_featured_logo.png'},
  {name: 'Cadillac', image: './assets/cadillac_featured_logo.png'},
  {name: 'Chevrolet', image: './assets/chevrolet_featured_logo.png'},
  {name: 'Chrysler', image: './assets/chrysler_featured_logo.png'},
  {name: 'Dodge', image: './assets/dodge_featured_logo.png'},
  {name: 'Ferrari', image: './assets/ferrari_featured_logo.png'},
  {name: 'Fiat', image: './assets/fiat_featured_logo.png'},
  {name: 'Ford', image: './assets/ford_featured_logo.png'},
  {name: 'Genesis', image: './assets/genesis_featured_logo.png'},
  {name: 'GMC', image: './assets/gmc_featured_logo.png'},
  {name: 'Honda', image: './assets/honda_featured_logo.png'},
  {name: 'Hyundai', image: './assets/hyundai_featured_logo.png'},
  {name: 'Infinity', image: './assets/infiniti_featured_logo.png'},
  {name: 'Jaguar', image: './assets/jaguar_featured_logo.png'},
  {name: 'Jeep', image: './assets/jeep_featured_logo.png'},
  {name: 'Kia', image: './assets/kia_featured_logo.png'},
  {name: 'Lamborghini', image: './assets/lamborghini_featured_logo.png'},
  {name: 'Land Rover', image: './assets/landrover_featured_logo.png'},
  {name: 'Lexus', image: './assets/lexus_featured_logo.png'},
  {name: 'Lincoln', image: './assets/lincoln_featured_logo.png'},
  {name: 'Maserati', image: './assets/maserati_featured_logo.png'},
  {name: 'Mazda', image: './assets/mazda_featured_logo.png'},
  {name: 'Mclaren', image: './assets/mclaren_featured_logo.png'},
  {name: 'Mercedes Benz', image: './assets/mercedesbenz_featured_logo.png'},
  {name: 'Mini', image: './assets/mini_featured_logo.png'},
  {name: 'Mitsubishi', image: './assets/mitsubishi_featured_logo.png'},
  {name: 'Nissan', image: './assets/nissan_featured_logo.png'},
  {name: 'Porsche', image: './assets/porsche_featured_logo.png'},
  {name: 'Ram', image: './assets/ram_featured_logo.png'},
  {name: 'Rolls Royce', image: './assets/rollsroyce_featured_logo.png'},
  {name: 'Smart', image: './assets/smart_featured_logo.png'},
  {name: 'Subaru', image: './assets/subaru_featured_logo.png'},
  {name: 'Tesla', image: './assets/tesla_featured_logo.png'},
  {name: 'Toyota', image: './assets/toyota_featured_logo.png'},
  {name: 'Volkswagen', image: './assets/volkswagen_featured_logo.png'},
  {name: 'Volvo', image: './assets/volvo_featured_logo.png'}
]

export default {
  getAllVehicles: () => vehicles
}
